name: Create commits
on:
  workflow_dispatch:
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create commits
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-action@users.noreply.github.com"
          git checkout -b feature/new-pr
          git push -u origin feature/new-pr
          date +%s > report.txt
          git add .
          git commit -m "Modify tracked file during workflow"
          git push
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
